# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e609e711961f68918c5fa8eadbed9f5fc2dd367e1060fdf471539bd2cf74ef426237d77e1259145f9e15cf343b592a2ee4e55b8eb7f33f4c00019d1223e1be

test:
  secret_key_base: 4db0b03d66294c0881259f8f6e1da5f723730f03ed13b5a39505332fcb3ace01ac55e3f729eef5365d91e5665cb24e8dfbc968644bd3bb933f3a48ed80e3725e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
